// Built-in examples (copied from tests/fixtures/po_*). In the breakfast domain,
// coffee and toast are unordered: they interleave in the partial-order plan, and
// run in parallel in the timed plan, where brewing lasts 3 time units.
(function (root) {
  'use strict';
  const HTNV = root.HTNV = root.HTNV || {};
  HTNV.examples = [
    {
      "id": "po",
      "label": "Partial-order example",
      "plan": "==>\n1 grind arabica\n2 slice bread1\n4 toast bread1\n3 brew arabica cup1\nroot 10\n10 breakfast cup1 bread1 -> m-breakfast 11 12 13\n11 make-coffee cup1 -> m-coffee 1 3\n12 make-toast bread1 -> m-toast 2 4\n13 tidy -> m-tidy-nothing\n<==\n",
      "domain": ";; Tiny partial-order HTN domain used by the viewer tests.\n;; Coffee and toast are unordered (they may interleave); tidying comes last.\n(define (domain kitchen)\n  (:requirements :typing :hierarchy :negative-preconditions)\n  (:types cup beans bread - object)\n  (:predicates (ground ?b - beans) (coffee ?c - cup) (sliced ?b - bread)\n               (toasted ?b - bread) (has-beans ?b - beans) (clean) (dirty))\n\n  (:task breakfast :parameters (?c - cup ?br - bread))\n  (:task make-coffee :parameters (?c - cup))\n  (:task make-toast :parameters (?br - bread))\n  (:task tidy :parameters ())\n\n  (:method m-breakfast\n    :parameters (?c - cup ?br - bread)\n    :task (breakfast ?c ?br)\n    :subtasks (and (c (make-coffee ?c)) (t (make-toast ?br)) (s (tidy)))\n    :ordering (and (< c s) (< t s)))\n\n  (:method m-coffee\n    :parameters (?c - cup ?b - beans)\n    :task (make-coffee ?c)\n    :precondition (has-beans ?b)\n    :ordered-subtasks (and (grind ?b) (brew ?b ?c)))\n\n  (:method m-toast\n    :parameters (?br - bread)\n    :task (make-toast ?br)\n    :ordered-subtasks (and (slice ?br) (toast ?br)))\n\n  (:method m-tidy-nothing\n    :parameters ()\n    :task (tidy)\n    :precondition (not (dirty))\n    :subtasks ())\n\n  (:method m-tidy-wipe\n    :parameters ()\n    :task (tidy)\n    :precondition (dirty)\n    :subtasks (and (wipe)))\n\n  (:action grind :parameters (?b - beans)\n    :precondition (has-beans ?b)\n    :effect (and (ground ?b) (not (has-beans ?b))))\n  (:action brew :parameters (?b - beans ?c - cup)\n    :precondition (ground ?b)\n    :effect (and (coffee ?c) (not (ground ?b))))\n  (:action slice :parameters (?br - bread)\n    :precondition (not (sliced ?br))\n    :effect (sliced ?br))\n  (:action toast :parameters (?br - bread)\n    :precondition (sliced ?br)\n    :effect (and (toasted ?br)\n                 (forall (?b - beans) (when (ground ?b) (clean)))))\n  (:action wipe :parameters ()\n    :precondition (dirty)\n    :effect (and (clean) (not (dirty))))\n)\n",
      "problem": "(define (problem morning)\n  (:domain kitchen)\n  (:objects cup1 - cup arabica - beans bread1 - bread)\n  (:htn :parameters () :subtasks (and (task0 (breakfast cup1 bread1))))\n  (:init (has-beans arabica))\n  (:goal (and (coffee cup1) (toasted bread1)))\n)\n"
    },
    {
      "id": "timed",
      "label": "Example with durations",
      "plan": "==>\n1 grind arabica 0 1\n2 brew arabica cup1 1 4\n3 slice bread1 1 2\n4 toast bread1 2 3\nroot 10\n10 breakfast cup1 bread1 -> m-breakfast 11 12 13\n11 make-coffee cup1 -> m-coffee 1 2\n12 make-toast bread1 -> m-toast 3 4\n13 tidy -> m-tidy-nothing\n<==\n",
      "domain": ";; Tiny partial-order HTN domain used by the viewer tests.\n;; Coffee and toast are unordered (they may interleave); tidying comes last.\n(define (domain kitchen)\n  (:requirements :typing :hierarchy :negative-preconditions)\n  (:types cup beans bread - object)\n  (:predicates (ground ?b - beans) (coffee ?c - cup) (sliced ?b - bread)\n               (toasted ?b - bread) (has-beans ?b - beans) (clean) (dirty))\n\n  (:task breakfast :parameters (?c - cup ?br - bread))\n  (:task make-coffee :parameters (?c - cup))\n  (:task make-toast :parameters (?br - bread))\n  (:task tidy :parameters ())\n\n  (:method m-breakfast\n    :parameters (?c - cup ?br - bread)\n    :task (breakfast ?c ?br)\n    :subtasks (and (c (make-coffee ?c)) (t (make-toast ?br)) (s (tidy)))\n    :ordering (and (< c s) (< t s)))\n\n  (:method m-coffee\n    :parameters (?c - cup ?b - beans)\n    :task (make-coffee ?c)\n    :precondition (has-beans ?b)\n    :ordered-subtasks (and (grind ?b) (brew ?b ?c)))\n\n  (:method m-toast\n    :parameters (?br - bread)\n    :task (make-toast ?br)\n    :ordered-subtasks (and (slice ?br) (toast ?br)))\n\n  (:method m-tidy-nothing\n    :parameters ()\n    :task (tidy)\n    :precondition (not (dirty))\n    :subtasks ())\n\n  (:method m-tidy-wipe\n    :parameters ()\n    :task (tidy)\n    :precondition (dirty)\n    :subtasks (and (wipe)))\n\n  (:action grind :parameters (?b - beans)\n    :precondition (has-beans ?b)\n    :effect (and (ground ?b) (not (has-beans ?b))))\n  (:action brew :parameters (?b - beans ?c - cup)\n    :precondition (ground ?b)\n    :effect (and (coffee ?c) (not (ground ?b))))\n  (:action slice :parameters (?br - bread)\n    :precondition (not (sliced ?br))\n    :effect (sliced ?br))\n  (:action toast :parameters (?br - bread)\n    :precondition (sliced ?br)\n    :effect (and (toasted ?br)\n                 (forall (?b - beans) (when (ground ?b) (clean)))))\n  (:action wipe :parameters ()\n    :precondition (dirty)\n    :effect (and (clean) (not (dirty))))\n)\n",
      "problem": "(define (problem morning)\n  (:domain kitchen)\n  (:objects cup1 - cup arabica - beans bread1 - bread)\n  (:htn :parameters () :subtasks (and (task0 (breakfast cup1 bread1))))\n  (:init (has-beans arabica))\n  (:goal (and (coffee cup1) (toasted bread1)))\n)\n"
    }
  ];
})(typeof window !== 'undefined' ? window : globalThis);
